begin;
select plan(39);
select ok((select relrowsecurity from pg_class where oid = 'public.app_users'::regclass), 'app_users has RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.companies'::regclass), 'companies has RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.form_requests'::regclass), 'form_requests has RLS');
select ok(has_table_privilege('anon', 'public.companies', 'select') = false, 'anon cannot read companies');
select ok(has_table_privilege('authenticated', 'public.form_submissions', 'insert') = false, 'authenticated cannot insert history');
select ok(has_function_privilege('anon', 'public.submit_form_transaction(text,jsonb)', 'execute') = false, 'anon cannot execute submit RPC');
select ok(has_function_privilege('authenticated', 'public.submit_form_transaction(text,jsonb)', 'execute') = false, 'authenticated cannot execute submit RPC');
select ok(has_function_privilege('authenticated', 'public.create_form_request_transaction(uuid,text,uuid)', 'execute') = false, 'authenticated cannot execute create RPC');
select ok(has_function_privilege('anon', 'public.revoke_form_request_transaction(uuid,uuid)', 'execute') = false, 'anon cannot execute revoke RPC');
select ok(has_table_privilege('authenticated', 'public.audit_events', 'select'), 'authenticated can read audit events');
select ok(has_function_privilege('service_role', 'public.revoke_form_request_transaction(uuid,uuid)', 'execute'), 'service role can execute revoke RPC');
select ok(has_function_privilege('anon', 'public.inspect_expense_item_usage(uuid,uuid)', 'execute') = false, 'anon cannot inspect expense usage');
select ok(has_function_privilege('authenticated', 'public.inspect_expense_item_usage(uuid,uuid)', 'execute') = false, 'authenticated cannot inspect expense usage directly');
select ok(has_function_privilege('authenticated', 'public.delete_or_deactivate_expense_item(uuid,uuid,text)', 'execute') = false, 'authenticated cannot delete expense items directly');
select ok(has_function_privilege('service_role', 'public.delete_or_deactivate_expense_item(uuid,uuid,text)', 'execute'), 'service role can execute catalog removal RPC');
select ok((select count(*) from pg_policies where schemaname = 'public' and tablename = 'audit_events' and policyname = 'audit_events_select_admin') = 1, 'audit policy is admin-only');
select ok((select count(*) from pg_policies where schemaname = 'public' and tablename = 'audit_events' and policyname = 'audit_events_select_internal') = 0, 'general internal audit policy is absent');
select ok((select count(*) from public.expense_items) = 23, 'seed has 23 expense items');
select ok((select count(*) from public.form_content) = 1, 'seed has singleton content');
select ok((select count(*) from pg_indexes where indexname = 'form_requests_one_pending_per_company_idx') = 1, 'pending request index exists');
select ok((select count(*) from pg_trigger where tgname = 'history_form_submissions_immutable') = 1, 'submission immutability trigger exists');
select ok((select count(*) from pg_trigger where tgname = 'history_audit_immutable') = 1, 'audit immutability trigger exists');
select ok((select relrowsecurity from pg_class where oid = 'public.submission_revisions'::regclass), 'submission revisions have RLS');
select ok((select relrowsecurity from pg_class where oid = 'public.submission_revision_items'::regclass), 'submission revision items have RLS');
select ok(has_table_privilege('authenticated', 'public.submission_revisions', 'select'), 'authenticated can read revisions');
select ok(has_table_privilege('authenticated', 'public.submission_revision_items', 'select'), 'authenticated can read revision items');
select ok(has_function_privilege('anon', 'public.create_internal_submission_transaction(uuid,uuid,jsonb)', 'execute') = false, 'anon cannot create internal submissions');
select ok(has_function_privilege('authenticated', 'public.create_internal_submission_transaction(uuid,uuid,jsonb)', 'execute') = false, 'authenticated cannot create internal submissions directly');
select ok(has_function_privilege('anon', 'public.create_submission_revision_transaction(uuid,uuid,jsonb)', 'execute') = false, 'anon cannot create revisions');
select ok(has_function_privilege('authenticated', 'public.create_submission_revision_transaction(uuid,uuid,jsonb)', 'execute') = false, 'authenticated cannot create revisions directly');
select ok(has_function_privilege('anon', 'public.import_submission_transaction(uuid,uuid,uuid)', 'execute') = false, 'anon cannot import submissions');
select ok(has_function_privilege('authenticated', 'public.import_submission_transaction(uuid,uuid,uuid)', 'execute') = false, 'authenticated cannot import submissions directly');
select ok(has_function_privilege('service_role', 'public.create_internal_submission_transaction(uuid,uuid,jsonb)', 'execute'), 'service role can create internal submissions');
select ok(has_function_privilege('service_role', 'public.create_submission_revision_transaction(uuid,uuid,jsonb)', 'execute'), 'service role can create revisions');
select ok(has_function_privilege('service_role', 'public.import_submission_transaction(uuid,uuid,uuid)', 'execute'), 'service role can import submissions');
select ok((select count(*) from pg_trigger where tgname = 'history_submission_revisions_immutable') = 1, 'revision immutability trigger exists');
select ok((select count(*) from pg_trigger where tgname = 'history_submission_revision_items_immutable') = 1, 'revision item immutability trigger exists');
select ok((select count(*) from information_schema.columns where table_schema = 'public' and table_name = 'form_request_items' and column_name = 'initial_updated_at') = 1, 'request item freshness column exists');
select ok(position('max(sr.revision_number)' in pg_get_functiondef('public.create_submission_revision_transaction(uuid, uuid, jsonb)'::regprocedure)) > 0, 'revision number query qualifies its column reference');
select * from finish();
rollback;
